In [1]:
import pandas as pd
import os

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [2]:
root = "/Volumes/ArxivE/_Tobias/LSM980/Mitotic_Stopwatch" + "/"
outputFolder = root + "DataFrames" + "/"

In [3]:
# Parse mitotic error tables

error_path_1 = root + "Errors_siHAU6.xlsx"
error_path_2 = root + "Errors_siLUC1.xlsx"

error_paths = [error_path_1, error_path_2]

def parse_error(error_list = error_paths):
    dfs = []
    for path in error_list:
        df = pd.read_excel(path)
        dfs.append(df)
    return pd.concat(dfs)

error_df = parse_error()
error_df = error_df.replace({"T": True, "F": False, "R": False})#.rename(columns = {"Multipolar Spindle": "Multipolar", "Multipolar Divition": "Multipolar"})

error_df.head()

/var/folders/lr/cb1nd6l97696j8chvkss86580000gn/T/ipykernel_15118/632493335.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  error_df = error_df.replace({"T": True, "F": False, "R": False})#.rename(columns = {"Multipolar Spindle": "Multipolar", "Multipolar Divition": "Multipolar"})

,Source_ID,Dataset,Position,Laggings,Massive Missegregation,DNA bridge,Misaligned,MN,Multipolar Divition,Citokinesis Failure,Slippage,Mitotic Death,Comments
0,8825,20250724,6,True,False,False,False,True,False,True,False,False,check again
1,10714,20250724,6,False,False,False,False,False,False,False,False,False,NaN
2,9755,20250724,6,False,False,False,False,False,False,False,False,False,NaN
3,9330,20250724,6,False,False,False,False,False,False,False,False,False,NaN
4,9630,20250724,6,False,False,False,False,False,False,False,False,False,NaN

In [5]:
df = pd.read_csv('/Volumes/ArxivE/_Tobias/LSM980/Mitotic_Stopwatch/DataFrames/MainDataFrame_Lineages_Augmin.csv')
df.columns

Index(['Unnamed: 0', 'Track_ID', 'Source_ID', 'Splitting_event', 'Lineage',
       'Track_Coordinate_X', 'Track_Coordinate_Y', 'Frame', 'Position',
       'Dataset', 'Generation', 'Mother_ID', 'Grandmother_ID', 'Sister_ID',
       'Cell_Cycle_mins', 'Cell_Cycle_hours', 'Seen_sister', 'Seen_granny'],
      dtype='object')

In [7]:
def getonsets(filepath, position, dataset):
    onsets = pd.read_csv(filepath)
    onsets["Source_ID"] = onsets.Label.str.split(":").str.get(1).astype(int)
    onsets["Position"] = position
    onsets["Dataset"] = dataset
    onsets.rename(columns = {"Slice": "Frame_onset"}, inplace = True)
    return onsets

# Define metadata for each file
onsets_info = [
    {"date": "20250724", "position": 2, "target": "LUC1", "file": "20250724_IM_H2B-GFP_MitoStop_RNAi03_onsets.csv"},
    {"date": "20250724", "position": 3, "target": "LUC1", "file": "20250724_IM_H2B-GFP_MitoStop_RNAi03_onsets.csv"},
    {"date": "20250724", "position": 4, "target": "LUC1", "file": "20250724_IM_H2B-GFP_MitoStop_RNAi03_onsets.csv"},
    {"date": "20250724", "position": 5, "target": "LUC1", "file": "20250724_IM_H2B-GFP_MitoStop_RNAi03_onsets.csv"},
    {"date": "20250724", "position": 6, "target": "HAUS6", "file": "20250724_IM_H2B-GFP_MitoStop_RNAi03_onsets.csv"},
    {"date": "20250724", "position": 7, "target": "HAUS6", "file": "20250724_IM_H2B-GFP_MitoStop_RNAi03_onsets.csv"},
    {"date": "20250724", "position": 8, "target": "HAUS6", "file": "20250724_IM_H2B-GFP_MitoStop_RNAi03_onsets.csv"},
    {"date": "20250724", "position": 9, "target": "HAUS6", "file": "20250724_IM_H2B-GFP_MitoStop_RNAi03_onsets.csv"},
    
    {"date": "20250807", "position": 2, "target": "LUC1", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},
    {"date": "20250807", "position": 3, "target": "LUC1", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},
    {"date": "20250807", "position": 4, "target": "LUC1", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},
    {"date": "20250807", "position": 5, "target": "HAUS6", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},
    {"date": "20250807", "position": 6, "target": "HAUS6", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},
    {"date": "20250807", "position": 7, "target": "HAUS6", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},
    {"date": "20250807", "position": 8, "target": "HAUS6", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},
    {"date": "20250807", "position": 9, "target": "HAUS6", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},

    {"date": "20250814", "position": 2, "target": "LUC1", "file": "20250814_IM_H2B-GFP_MitoStop_RNAi05_onsets.csv"},
    {"date": "20250814", "position": 3, "target": "LUC1", "file": "20250814_IM_H2B-GFP_MitoStop_RNAi05_onsets.csv"},
    {"date": "20250814", "position": 4, "target": "LUC1", "file": "20250814_IM_H2B-GFP_MitoStop_RNAi05_onsets.csv"},
    {"date": "20250814", "position": 5, "target": "HAUS6", "file": "20250814_IM_H2B-GFP_MitoStop_RNAi05_onsets.csv"},
    {"date": "20250814", "position": 6, "target": "HAUS6", "file": "20250814_IM_H2B-GFP_MitoStop_RNAi05_onsets.csv"},
    {"date": "20250814", "position": 7, "target": "HAUS6", "file": "20250814_IM_H2B-GFP_MitoStop_RNAi05_onsets.csv"},
    {"date": "20250814", "position": 8, "target": "HAUS6", "file": "20250814_IM_H2B-GFP_MitoStop_RNAi05_onsets.csv"},
   # {"date": "20250814", "position": 9, "target": "HAUS6", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},
]

# Generate and combine dataframes
df_onsets_list = []

for info in onsets_info:
    folder = f"{root}/{info['date']}/Position_{info['position']}_si{info['target']}/Concatenated"
    filepath = os.path.join(folder, info["file"])
    df_single = getonsets(filepath, info["position"], info["date"])
    df_onsets_list.append(df_single)

df_onsets = pd.concat(df_onsets_list, ignore_index = True)
df_onsets["Dataset"] = df_onsets.Dataset.astype(int)

df_onsets.head()

,,Label,X,Y,Frame_onset,Source_ID,Position,Dataset
0,1,tomeasure:2989:98,1034.147,568.449,98,2989,2,20250724
1,2,tomeasure:3052:105,1055.691,417.636,105,3052,2,20250724
2,3,tomeasure:2005:109,662.915,696.060,109,2005,2,20250724
3,4,tomeasure:2121:108,515.416,613.196,108,2121,2,20250724
4,5,tomeasure:2902:110,918.965,517.073,110,2902,2,20250724

In [8]:
df["Frame"] = df.Frame.astype(int) + 1 #otherwise the trackmate and mitotic timing frames are not aligned

df = df.merge(df_onsets, how = "outer")

,Unnamed: 0,Track_ID,Source_ID,Splitting_event,Lineage,Track_Coordinate_X,Track_Coordinate_Y,Frame,Position,Dataset,...,Sister_ID,Cell_Cycle_mins,Cell_Cycle_hours,Seen_sister,Seen_granny,,Label,X,Y,Frame_onset
0,0,0,2004,True,2004,811.656027,757.794218,297,8,20250814,...,NaN,NaN,NaN,NaN,NaN,16,tomeasure:2004:286,806.270,752.408,286
1,0,0,2005,True,2005,666.091036,713.323699,118,2,20250724,...,NaN,NaN,NaN,NaN,NaN,3,tomeasure:2005:109,662.915,696.060,109
2,0,0,2008,True,2008,1066.878136,654.766245,59,2,20250807,...,NaN,NaN,NaN,NaN,NaN,29,tomeasure:2008:53,1082.208,647.170,53
3,2,0,2026,True,2004.2026,783.482158,819.666245,736,8,20250814,...,2045.0,3073.0,51.216667,False,NaN,58,tomeasure:2026:671,898.249,744.122,671
4,2,0,2027,True,2005.2027,662.224034,670.786681,534,2,20250724,...,NaN,2912.0,48.533333,NaN,NaN,26,tomeasure:2027:523,604.081,651.314,523
5,2,0,2034,True,2008.2034,1076.821855,666.919679,316,2,20250807,...,NaN,1799.0,29.983333,NaN,NaN,13,tomeasure:2034:306,1094.638,669.544,306
6,4,0,2045,True,2004.2045,685.702259,925.180147,663,8,20250814,...,2026.0,2562.0,42.700000,True,NaN,52,tomeasure:2045:642,687.774,928.909,642
7,4,0,2053,True,2008.2034.2053,1014.949828,722.162560,580,2,20250807,...,NaN,1848.0,30.800000,NaN,False,28,tomeasure:2053:568,1020.888,717.605,568
8,6,1,2080,True,2080,1052.514987,869.108623,141,2,20250807,...,NaN,NaN,NaN,NaN,NaN,2,tomeasure:2080:133,1064.807,870.075,133
9,6,1,2080,True,2080,810.551169,887.614988,327,8,20250814,...,NaN,NaN,NaN,NaN,NaN,22,tomeasure:2080:317,817.042,878.362,317
10,4,1,2096,True,2096,518.040115,698.960550,211,2,20250724,...,NaN,NaN,NaN,NaN,NaN,11,tomeasure:2096:201,528.674,692.746,201
11,8,1,2096,True,2080.2096,744.812141,872.699410,622,8,20250814,...,2118.0,2065.0,34.416667,True,NaN,45,tomeasure:2096:609,690.260,901.564,609
12,8,1,2097,True,2080.2097,884.576630,1311.051670,597,2,20250807,...,NaN,3192.0,53.200000,NaN,NaN,31,tomeasure:2097:587,885.820,1316.714,587
13,10,1,2118,True,2080.2118,872.423196,863.860549,601,8,20250814,...,2096.0,1918.0,31.966667,False,NaN,41,tomeasure:2118:587,891.620,855.988,587
14,6,2,2121,True,2121,499.809964,637.640952,119,2,20250724,...,NaN,NaN,NaN,NaN,NaN,4,tomeasure:2121:108,515.416,613.196,108
15,10,3,2152,True,2152,380.761556,880.157199,626,2,20250807,...,NaN,NaN,NaN,NaN,NaN,32,tomeasure:2152:617,385.319,868.418,617
16,8,3,2153,True,2153,874.632911,867.175122,4,2,20250724,...,NaN,NaN,NaN,NaN,NaN,15,tomeasure:2153:1,869.247,863.446,1
17,12,2,2157,True,2157,618.858373,1000.862894,488,8,20250814,...,NaN,NaN,NaN,NaN,NaN,34,tomeasure:2157:465,624.797,1015.088,465
18,12,3,2168,True,2152.2168,405.068424,1228.187348,849,2,20250807,...,NaN,1561.0,26.016667,NaN,NaN,56,tomeasure:2168:842,408.521,1244.622,842
19,14,3,2186,True,2186,608.362225,942.305440,117,8,20250814,...,NaN,NaN,NaN,NaN,NaN,1,tomeasure:2186:106,627.283,945.482,106

In [9]:
sorted_df = df.sort_values(by = ["Frame", "Frame_onset"], ascending = True)
sorted_df.head(10)

,Unnamed: 0,Track_ID,Source_ID,Splitting_event,Lineage,Track_Coordinate_X,Track_Coordinate_Y,Frame,Position,Dataset,...,Sister_ID,Cell_Cycle_mins,Cell_Cycle_hours,Seen_sister,Seen_granny,,Label,X,Y,Frame_onset
16,8,3,2153,True,2153,874.632911,867.175122,4,2,20250724,...,NaN,NaN,NaN,NaN,NaN,15,tomeasure:2153:1,869.247,863.446,1
1063,52,14,11639,True,11639,800.055022,912.750499,7,9,20250807,...,NaN,NaN,NaN,NaN,NaN,24,tomeasure:11639:1,796.326,899.907,1
110,68,17,2908,True,2908,1172.115824,929.323363,11,2,20250807,...,NaN,NaN,NaN,NaN,NaN,1,tomeasure:2908:5,1167.558,918.965,5
174,0,0,3449,True,3449,876.842626,690.121689,13,3,20250807,...,NaN,NaN,NaN,NaN,NaN,5,tomeasure:3449:1,885.820,676.173,1
471,112,28,5596,True,5596,1147.532742,897.006278,13,8,20250814,...,NaN,NaN,NaN,NaN,NaN,2,tomeasure:5596:5,1131.927,904.878,5
879,168,25,9829,True,9829,614.715157,866.622693,14,6,20250724,...,NaN,NaN,NaN,NaN,NaN,8,tomeasure:9829:9,614.853,865.932,9
306,82,15,4535,True,4535,833.200750,878.776127,15,3,20250807,...,NaN,NaN,NaN,NaN,NaN,6,tomeasure:4535:8,819.528,868.418,8
242,44,9,4005,True,4005,1098.366578,853.088188,16,3,20250807,...,NaN,NaN,NaN,NaN,NaN,9,tomeasure:4005:1,876.705,674.516,1
426,92,23,5300,True,5300,815.523029,1106.929225,16,8,20250814,...,NaN,NaN,NaN,NaN,NaN,4,tomeasure:5300:10,810.413,1110.382,10
767,6,5,8681,True,8681,863.031906,758.622861,17,7,20250807,...,NaN,NaN,NaN,NaN,NaN,4,tomeasure:8681:10,858.474,754.065,10

In [10]:
df["Frames_in_mitosis"] = (df.Frame - df.Frame_onset.astype(int))
df["Mitotic_duration_mins"] = df.Frames_in_mitosis * 7

In [11]:
def getInterphaseDuration(x, dataframe = df):
    # should be the same as cell_cycle - mitotic duration
    daughter_time = x.Frame_onset
    if x.Generation < 2:
        return None
    else:
        mother_row = dataframe.loc[
            (dataframe.Dataset == x.Dataset) &
            (dataframe.Position == x.Position) &
            (dataframe.Source_ID == x.Mother_ID)
        ]
        if mother_row["Frame"].shape[0] == 1:   
            mother_time = mother_row["Frame"].item()
            interphase_duration = (int(daughter_time) - int(mother_time)) * 7
            return interphase_duration
        else:
            return None


def getMitoticDurationMother(x, dataframe = df):
    if x.Generation < 2:
        return None
    else:
        mother_row = dataframe.loc[
            (dataframe.Dataset == x.Dataset) &
            (dataframe.Position == x.Position) &
            (dataframe.Source_ID == x.Mother_ID)
        ]
        
        if len(mother_row) == 1:
            return mother_row.iloc[0].Mitotic_duration_mins
        else:
            return None


#def getMetaphaseArrest(x):
#    if x > 100:
#        return "> 100 min"
#   # elif x > 45:
#   #     return "045-90"
#    else:
#        return "< 100 min"
#
#def getMetaphaseArrest_mother(x):
#    if x > 0:
#        if x > 100:
#            return "> 100 min"
#       # elif x > 45:
#       #     return "045-90"
#        else:
#            return "< 100 min"
#    else:
#        pass

def getMetaphaseArrest(x):
    if x < 30:
        return "000-030 min"
    elif (x < 60) & (x > 30):
        return "030-060"
    elif (x < 90) & (x > 60):
        return "060-090"
    elif (x < 120) & (x > 90):
        return "090-120"
    else:
        return "> 120 min"

def getMetaphaseArrest_mother(x):
    if x > 0:
        if x < 30:
            return "000-030 min"
        elif (x < 60) & (x > 30):
            return "030-060"
        elif (x < 90) & (x > 60):
            return "060-090"
        elif (x < 120) & (x > 90):
            return "090-120"
        else:
            return "> 120 min"
    else:
        pass

df["Interphase_duration_mins"] = df.apply(getInterphaseDuration, axis = 1) 
df["Interphase_duration_hrs"] = df.Interphase_duration_mins / 60
df["Mitotic_duration_hrs"] = df.Mitotic_duration_mins / 60

df["Mother_Mitotic_duration_mins"] = df.apply(getMitoticDurationMother, axis = 1)
df["Mother_arrested"] = df.Mother_Mitotic_duration_mins.apply(getMetaphaseArrest_mother)
df["Metaphase_arrested"] = df.Mitotic_duration_mins.apply(getMetaphaseArrest)
df["Frame_onset_hrs"] = df.Frame_onset * 7 / 60 # Augmin depletion time at NEB
df["Frame_hrs"] = df.Frame * 7 / 60 # Augmin depletion time at anaphase

# Create Bins (one bin for every 12 h of depletion, binning cells with the same onset of mitotis)
interval_range_depletion = pd.interval_range(start = 0, freq = 12, end = 96) 
df['Augmin_depletion_bin'] = pd.cut(df['Frame_onset_hrs'], bins = interval_range_depletion).astype(str)

# Create Bins (one bin for every 30 min of mitotic duration) # kind of is the same as "Metaphase_arrested"
interval_range_mitosis = pd.interval_range(start = 0, freq = 30, end = 900) 
df['Mitotic_duration_bin'] = pd.cut(df['Mitotic_duration_mins'], bins = interval_range_mitosis).astype(str)

df["Unique_Track_ID"] = df.Dataset.astype(str) + df.Position.astype(str) + df.Track_ID.astype(str)
df["Unique_Source_ID"] = df.Dataset.astype(str) + df.Position.astype(str) + df.Source_ID.astype(str)

#df = df[df["Dataset"] == 20250814]

# TODO find out why some are wrong?!
df = df.drop(df[df.Cell_Cycle_hours < 1].index)
df = df.drop(df[df.Mitotic_duration_mins < 0].index)
df = df.drop(df[df.Mother_Mitotic_duration_mins < 0].index)

df.head()

,Unnamed: 0,Track_ID,Source_ID,Splitting_event,Lineage,Track_Coordinate_X,Track_Coordinate_Y,Frame,Position,Dataset,...,Mitotic_duration_hrs,Mother_Mitotic_duration_mins,Mother_arrested,Metaphase_arrested,Frame_onset_hrs,Frame_hrs,Augmin_depletion_bin,Mitotic_duration_bin,Unique_Track_ID,Unique_Source_ID
0,0,0,2004,True,2004,811.656027,757.794218,297,8,20250814,...,1.283333,NaN,None,060-090,33.366667,34.650000,"(24, 36]","(60, 90]",2025081480,2025081482004
1,0,0,2005,True,2005,666.091036,713.323699,118,2,20250724,...,1.050000,NaN,None,060-090,12.716667,13.766667,"(12, 24]","(60, 90]",2025072420,2025072422005
2,0,0,2008,True,2008,1066.878136,654.766245,59,2,20250807,...,0.700000,NaN,None,030-060,6.183333,6.883333,"(0, 12]","(30, 60]",2025080720,2025080722008
3,2,0,2026,True,2004.2026,783.482158,819.666245,736,8,20250814,...,7.583333,77.0,060-090,> 120 min,78.283333,85.866667,"(72, 84]","(450, 480]",2025081480,2025081482026
4,2,0,2027,True,2005.2027,662.224034,670.786681,534,2,20250724,...,1.283333,63.0,060-090,060-090,61.016667,62.300000,"(60, 72]","(60, 90]",2025072420,2025072422027

In [12]:
def getCondition(x):
    if x.Dataset == 20250724:
        if x.Position < 6:
            return "siLUC1"
        else:
            return "siHAUS6"

    elif x.Dataset == 20250807 or x.Dataset == 20250814:
        if x.Position < 5:
            return "siLUC1"
        else:
            return "siHAUS6"

df["Condition"] = df.apply(getCondition, axis = 1)

In [13]:
#selected_df = df[["Dataset", "Source_ID", "Position", "Frame", "Frame_onset", "X", "Y"]]

#selected_df.to_csv(outputFolder + "SelectedDataFrame_MitoticStopwatch_Augmin.csv")

In [14]:
df = df.merge(error_df, how = "outer")
df_eval = df.merge(error_df, how = "inner")
df.columns

Index(['Unnamed: 0', 'Track_ID', 'Source_ID', 'Splitting_event', 'Lineage',
       'Track_Coordinate_X', 'Track_Coordinate_Y', 'Frame', 'Position',
       'Dataset', 'Generation', 'Mother_ID', 'Grandmother_ID', 'Sister_ID',
       'Cell_Cycle_mins', 'Cell_Cycle_hours', 'Seen_sister', 'Seen_granny',
       ' ', 'Label', 'X', 'Y', 'Frame_onset', 'Frames_in_mitosis',
       'Mitotic_duration_mins', 'Interphase_duration_mins',
       'Interphase_duration_hrs', 'Mitotic_duration_hrs',
       'Mother_Mitotic_duration_mins', 'Mother_arrested', 'Metaphase_arrested',
       'Frame_onset_hrs', 'Frame_hrs', 'Augmin_depletion_bin',
       'Mitotic_duration_bin', 'Unique_Track_ID', 'Unique_Source_ID',
       'Condition', 'Laggings', 'Massive Missegregation', 'DNA bridge',
       'Misaligned', 'MN', 'Multipolar Divition', 'Citokinesis Failure',
       'Slippage', 'Mitotic Death', 'Comments'],
      dtype='object')

In [15]:
df.to_csv(outputFolder + "MainDataFrame_MitoticStopwatch_Augmin.csv")
df_eval.to_csv(outputFolder + "MainDataFrame_MitoticStopwatch_Augmin_only_errors.csv")

print("Finished.")

Finished.