In [16]:
import pandas as pd
import os

In [17]:
root = "/Volumes/ArxivE/_Tobias/LSM980/Mitotic_Stopwatch" + "/"
outputFolder = root + "DataFrames" + "/"

In [18]:
# Parse mitotic error tables

error_path_1 = root + "20250724/Errors_siHAU6.xlsx"
error_path_2 = root + "20250724/Errors_siLUC1.xlsx"

error_paths = [error_path_1, error_path_2]

def parse_error(error_list = error_paths):
    dfs = []
    for path in error_list:
        df = pd.read_excel(path)
        dfs.append(df)
    return pd.concat(dfs)

error_df = parse_error()
error_df.head()

,Source_ID,Dataset,Position,Segregation Error,Multipolar Divition,Citokinesis Failure,Slippage,Mitotic Death,Comments,Multipolar Spindle
0,8825,20250724,6,True,False,True,False,False,check again,NaN
1,10714,20250724,6,False,False,False,False,False,NaN,NaN
2,9755,20250724,6,False,False,False,False,False,NaN,NaN
3,9330,20250724,6,False,False,False,False,False,NaN,NaN
4,9630,20250724,6,False,False,False,False,False,NaN,NaN

In [19]:
error_df.dtypes

Source_ID               int64
Dataset                 int64
Position                int64
Segregation Error        bool
Multipolar Divition    object
Citokinesis Failure      bool
Slippage                 bool
Mitotic Death            bool
Comments               object
Multipolar Spindle     object
dtype: object

In [20]:
df = pd.read_csv('/Volumes/ArxivE/_Tobias/LSM980/Mitotic_Stopwatch/DataFrames/MainDataFrame_Lineages_Augmin.csv')
df.columns

Index(['Unnamed: 0', 'Track_ID', 'Source_ID', 'Splitting_event', 'Lineage',
       'Track_Coordinate_X', 'Track_Coordinate_Y', 'Frame', 'Position',
       'Dataset', 'Generation', 'Mother_ID', 'Grandmother_ID', 'Sister_ID',
       'Cell_Cycle_mins', 'Cell_Cycle_hours', 'Seen_sister', 'Seen_granny'],
      dtype='object')

In [21]:
df.dtypes

Unnamed: 0              int64
Track_ID                int64
Source_ID               int64
Splitting_event          bool
Lineage                object
Track_Coordinate_X    float64
Track_Coordinate_Y    float64
Frame                   int64
Position                int64
Dataset                 int64
Generation              int64
Mother_ID             float64
Grandmother_ID        float64
Sister_ID             float64
Cell_Cycle_mins       float64
Cell_Cycle_hours      float64
Seen_sister            object
Seen_granny            object
dtype: object

In [22]:
def getonsets(filepath, position, dataset):
    onsets = pd.read_csv(filepath)
    onsets["Source_ID"] = onsets.Label.str.split(":").str.get(1).astype(int)
    onsets["Position"] = position
    onsets["Dataset"] = dataset
    onsets.rename(columns = {"Slice": "Frame_onset"}, inplace = True)
    return onsets

# Define metadata for each file
onsets_info = [
    {"date": "20250724", "position": 2, "target": "LUC1", "file": "20250724_IM_H2B-GFP_MitoStop_RNAi03_onsets.csv"},
    {"date": "20250724", "position": 3, "target": "LUC1", "file": "20250724_IM_H2B-GFP_MitoStop_RNAi03_onsets.csv"},
    {"date": "20250724", "position": 4, "target": "LUC1", "file": "20250724_IM_H2B-GFP_MitoStop_RNAi03_onsets.csv"},
    {"date": "20250724", "position": 5, "target": "LUC1", "file": "20250724_IM_H2B-GFP_MitoStop_RNAi03_onsets.csv"},
    {"date": "20250724", "position": 6, "target": "HAUS6", "file": "20250724_IM_H2B-GFP_MitoStop_RNAi03_onsets.csv"},
    {"date": "20250724", "position": 7, "target": "HAUS6", "file": "20250724_IM_H2B-GFP_MitoStop_RNAi03_onsets.csv"},
    {"date": "20250724", "position": 8, "target": "HAUS6", "file": "20250724_IM_H2B-GFP_MitoStop_RNAi03_onsets.csv"},
    {"date": "20250724", "position": 9, "target": "HAUS6", "file": "20250724_IM_H2B-GFP_MitoStop_RNAi03_onsets.csv"},
    
    {"date": "20250807", "position": 2, "target": "LUC1", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},
    {"date": "20250807", "position": 3, "target": "LUC1", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},
    {"date": "20250807", "position": 4, "target": "LUC1", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},
    {"date": "20250807", "position": 5, "target": "HAUS6", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},
    {"date": "20250807", "position": 6, "target": "HAUS6", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},
    {"date": "20250807", "position": 7, "target": "HAUS6", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},
    {"date": "20250807", "position": 8, "target": "HAUS6", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},
    {"date": "20250807", "position": 9, "target": "HAUS6", "file": "20250807_IM_H2B-GFP_MitoStop_RNAi04_onsets.csv"},
]

# Generate and combine dataframes
df_onsets_list = []

for info in onsets_info:
    folder = f"{root}/{info['date']}/Position_{info['position']}_si{info['target']}/Concatenated"
    filepath = os.path.join(folder, info["file"])
    df_single = getonsets(filepath, info["position"], info["date"])
    df_onsets_list.append(df_single)

df_onsets = pd.concat(df_onsets_list, ignore_index = True)
df_onsets["Dataset"] = df_onsets.Dataset.astype(int)

df_onsets.head()

,,Label,X,Y,Frame_onset,Source_ID,Position,Dataset
0,1,tomeasure:2989:98,1034.147,568.449,98,2989,2,20250724
1,2,tomeasure:3052:105,1055.691,417.636,105,3052,2,20250724
2,3,tomeasure:2005:109,662.915,696.060,109,2005,2,20250724
3,4,tomeasure:2121:108,515.416,613.196,108,2121,2,20250724
4,5,tomeasure:2902:110,918.965,517.073,110,2902,2,20250724

In [23]:
df["Frame"] = df.Frame.astype(int) + 1 #otherwise the trackmate and mitotic timing frames are not aligned

df = df.merge(df_onsets, how = "outer")

df.head(20)

,Unnamed: 0,Track_ID,Source_ID,Splitting_event,Lineage,Track_Coordinate_X,Track_Coordinate_Y,Frame,Position,Dataset,...,Sister_ID,Cell_Cycle_mins,Cell_Cycle_hours,Seen_sister,Seen_granny,,Label,X,Y,Frame_onset
0,0.0,0.0,2005,True,2005,666.091036,713.323699,118.0,2,20250724,...,NaN,NaN,NaN,NaN,NaN,3,tomeasure:2005:109,662.915,696.060,109
1,0.0,0.0,2008,True,2008,1066.878136,654.766245,59.0,2,20250807,...,NaN,NaN,NaN,NaN,NaN,29,tomeasure:2008:53,1082.208,647.170,53
2,2.0,0.0,2027,True,2005.2027,662.224034,670.786681,534.0,2,20250724,...,NaN,2912.0,48.533333,NaN,NaN,26,tomeasure:2027:523,604.081,651.314,523
3,2.0,0.0,2034,True,2008.2034,1076.821855,666.919679,316.0,2,20250807,...,NaN,1799.0,29.983333,NaN,NaN,13,tomeasure:2034:306,1094.638,669.544,306
4,4.0,0.0,2053,True,2008.2034.2053,1014.949828,722.162560,580.0,2,20250807,...,NaN,1848.0,30.800000,NaN,False,28,tomeasure:2053:568,1020.888,717.605,568
5,6.0,1.0,2080,True,2080,1052.514987,869.108623,141.0,2,20250807,...,NaN,NaN,NaN,NaN,NaN,2,tomeasure:2080:133,1064.807,870.075,133
6,4.0,1.0,2096,True,2096,518.040115,698.960550,211.0,2,20250724,...,NaN,NaN,NaN,NaN,NaN,11,tomeasure:2096:201,528.674,692.746,201
7,8.0,1.0,2097,True,2080.2097,884.576630,1311.051670,597.0,2,20250807,...,NaN,3192.0,53.200000,NaN,NaN,31,tomeasure:2097:587,885.820,1316.714,587
8,6.0,2.0,2121,True,2121,499.809964,637.640952,119.0,2,20250724,...,NaN,NaN,NaN,NaN,NaN,4,tomeasure:2121:108,515.416,613.196,108
9,10.0,3.0,2152,True,2152,380.761556,880.157199,626.0,2,20250807,...,NaN,NaN,NaN,NaN,NaN,32,tomeasure:2152:617,385.319,868.418,617
10,8.0,3.0,2153,True,2153,874.632911,867.175122,4.0,2,20250724,...,NaN,NaN,NaN,NaN,NaN,15,tomeasure:2153:1,869.247,863.446,1
11,12.0,3.0,2168,True,2152.2168,405.068424,1228.187348,849.0,2,20250807,...,NaN,1561.0,26.016667,NaN,NaN,56,tomeasure:2168:842,408.521,1244.622,842
12,10.0,4.0,2194,True,2194,1175.706612,956.392375,143.0,2,20250724,...,NaN,NaN,NaN,NaN,NaN,6,tomeasure:2194:134,1170.044,945.482,134
13,14.0,4.0,2197,True,2197,653.661388,1037.046981,147.0,2,20250807,...,NaN,NaN,NaN,NaN,NaN,4,tomeasure:2197:140,641.370,1034.975,140
14,12.0,4.0,2207,True,2194.2207,1234.540280,951.696730,383.0,2,20250724,...,2267.0,1680.0,28.000000,True,NaN,16,tomeasure:2207:374,1237.993,954.597,374
15,14.0,4.0,2223,True,2194.2207.2223,1243.379141,1006.387182,797.0,2,20250724,...,2243.0,2898.0,48.300000,False,True,45,tomeasure:2223:788,1244.622,1010.945,788
16,16.0,4.0,2231,True,2197.2231,1073.507282,951.972944,560.0,2,20250807,...,NaN,2891.0,48.183333,NaN,NaN,27,tomeasure:2231:551,1034.147,991.886,551
17,16.0,4.0,2243,True,2194.2207.2243,1335.082323,1034.561051,636.0,2,20250724,...,2223.0,1771.0,29.516667,True,True,33,tomeasure:2243:628,1352.346,1045.748,628
18,18.0,4.0,2260,True,2197.2231.2260,1196.146478,811.656027,858.0,2,20250807,...,2295.0,2086.0,34.766667,False,False,57,tomeasure:2260:848,1175.016,840.244,848
19,18.0,4.0,2267,True,2194.2267,1180.402257,943.962727,388.0,2,20250724,...,2207.0,1715.0,28.583333,False,NaN,17,tomeasure:2267:381,1175.016,955.426,381

In [24]:
sorted_df = df.sort_values(by = ["Frame", "Frame_onset"], ascending = True)
sorted_df.head(10)

,Unnamed: 0,Track_ID,Source_ID,Splitting_event,Lineage,Track_Coordinate_X,Track_Coordinate_Y,Frame,Position,Dataset,...,Sister_ID,Cell_Cycle_mins,Cell_Cycle_hours,Seen_sister,Seen_granny,,Label,X,Y,Frame_onset
10,8.0,3.0,2153,True,2153,874.632911,867.175122,4.0,2,20250724,...,NaN,NaN,NaN,NaN,NaN,15,tomeasure:2153:1,869.247,863.446,1
71,68.0,17.0,2908,True,2908,1172.115824,929.323363,11.0,2,20250807,...,NaN,NaN,NaN,NaN,NaN,1,tomeasure:2908:5,1167.558,918.965,5
117,0.0,0.0,3449,True,3449,876.842626,690.121689,13.0,3,20250807,...,NaN,NaN,NaN,NaN,NaN,5,tomeasure:3449:1,885.820,676.173,1
606,168.0,25.0,9829,True,9829,614.715157,866.622693,14.0,6,20250724,...,NaN,NaN,NaN,NaN,NaN,8,tomeasure:9829:9,614.853,865.932,9
210,82.0,15.0,4535,True,4535,833.200750,878.776127,15.0,3,20250807,...,NaN,NaN,NaN,NaN,NaN,6,tomeasure:4535:8,819.528,868.418,8
165,44.0,9.0,4005,True,4005,1098.366578,853.088188,16.0,3,20250807,...,NaN,NaN,NaN,NaN,NaN,9,tomeasure:4005:1,876.705,674.516,1
523,6.0,5.0,8681,True,8681,863.031906,758.622861,17.0,7,20250807,...,NaN,NaN,NaN,NaN,NaN,4,tomeasure:8681:10,858.474,754.065,10
339,66.0,16.0,5993,True,5993,1029.589192,1059.420347,17.0,4,20250807,...,NaN,NaN,NaN,NaN,NaN,2,tomeasure:5993:11,1025.032,1058.177,11
502,180.0,47.0,7990,True,7990,747.574285,1328.729392,18.0,5,20250724,...,NaN,NaN,NaN,NaN,NaN,11,tomeasure:7990:11,744.122,1333.287,11
79,76.0,18.0,2997,True,2997,1115.768086,1060.248991,19.0,2,20250807,...,NaN,NaN,NaN,NaN,NaN,7,tomeasure:2997:12,1111.211,1057.349,12

In [25]:
df["Frames_in_mitosis"] = (df.Frame - df.Frame_onset.astype(int))
df["Mitotic_duration_mins"] = df.Frames_in_mitosis * 7

In [26]:
def getInterphaseDuration(x, dataframe = df):
    # should be the same as cell_cycle - mitotic duration
    daughter_time = x.Frame_onset
    if x.Generation < 2:
        return None
    else:
        mother_row = dataframe.loc[
            (dataframe.Dataset == x.Dataset) &
            (dataframe.Position == x.Position) &
            (dataframe.Source_ID == x.Mother_ID)
        ]
        if mother_row["Frame"].shape[0] == 1:   
            mother_time = mother_row["Frame"].item()
            interphase_duration = (int(daughter_time) - int(mother_time)) * 7
            return interphase_duration
        else:
            return None


def getMitoticDurationMother(x, dataframe = df):
    if x.Generation < 2:
        return None
    else:
        mother_row = dataframe.loc[
            (dataframe.Dataset == x.Dataset) &
            (dataframe.Position == x.Position) &
            (dataframe.Source_ID == x.Mother_ID)
        ]
        
        if len(mother_row) == 1:
            return mother_row.iloc[0].Mitotic_duration_mins
        else:
            return None


#def getMetaphaseArrest(x):
#    if x > 100:
#        return "> 100 min"
#   # elif x > 45:
#   #     return "045-90"
#    else:
#        return "< 100 min"
#
#def getMetaphaseArrest_mother(x):
#    if x > 0:
#        if x > 100:
#            return "> 100 min"
#       # elif x > 45:
#       #     return "045-90"
#        else:
#            return "< 100 min"
#    else:
#        pass

def getMetaphaseArrest(x):
    if x < 30:
        return "000-030 min"
    elif (x < 60) & (x > 30):
        return "030-060"
    elif (x < 90) & (x > 60):
        return "060-090"
    elif (x < 120) & (x > 90):
        return "090-120"
    else:
        return "> 120 min"

def getMetaphaseArrest_mother(x):
    if x > 0:
        if x < 30:
            return "000-030 min"
        elif (x < 60) & (x > 30):
            return "030-060"
        elif (x < 90) & (x > 60):
            return "060-090"
        elif (x < 120) & (x > 90):
            return "090-120"
        else:
            return "> 120 min"
    else:
        pass

df["Interphase_duration_mins"] = df.apply(getInterphaseDuration, axis = 1) 
df["Interphase_duration_hrs"] = df.Interphase_duration_mins / 60
df["Mitotic_duration_hrs"] = df.Mitotic_duration_mins / 60

df["Mother_Mitotic_duration_mins"] = df.apply(getMitoticDurationMother, axis = 1)
df["Mother_arrested"] = df.Mother_Mitotic_duration_mins.apply(getMetaphaseArrest_mother)
df["Metaphase_arrested"] = df.Mitotic_duration_mins.apply(getMetaphaseArrest)
df["Frame_onset_hrs"] = df.Frame_onset * 7 / 60 # Augmin depletion time at NEB
df["Frame_hrs"] = df.Frame * 7 / 60 # Augmin depletion time at anaphase

# Create Bins (one bin for every 12 h of depletion, binning cells with the same onset of mitotis)
interval_range_depletion = pd.interval_range(start = 0, freq = 12, end = 96) 
df['Augmin_depletion_bin'] = pd.cut(df['Frame_onset_hrs'], bins = interval_range_depletion).astype(str)

df.head()

,Unnamed: 0,Track_ID,Source_ID,Splitting_event,Lineage,Track_Coordinate_X,Track_Coordinate_Y,Frame,Position,Dataset,...,Mitotic_duration_mins,Interphase_duration_mins,Interphase_duration_hrs,Mitotic_duration_hrs,Mother_Mitotic_duration_mins,Mother_arrested,Metaphase_arrested,Frame_onset_hrs,Frame_hrs,Augmin_depletion_bin
0,0.0,0.0,2005,True,2005,666.091036,713.323699,118.0,2,20250724,...,63.0,NaN,NaN,1.050000,NaN,None,060-090,12.716667,13.766667,"(12, 24]"
1,0.0,0.0,2008,True,2008,1066.878136,654.766245,59.0,2,20250807,...,42.0,NaN,NaN,0.700000,NaN,None,030-060,6.183333,6.883333,"(0, 12]"
2,2.0,0.0,2027,True,2005.2027,662.224034,670.786681,534.0,2,20250724,...,77.0,2835.0,47.250000,1.283333,63.0,060-090,060-090,61.016667,62.300000,"(60, 72]"
3,2.0,0.0,2034,True,2008.2034,1076.821855,666.919679,316.0,2,20250807,...,70.0,1729.0,28.816667,1.166667,42.0,030-060,060-090,35.700000,36.866667,"(24, 36]"
4,4.0,0.0,2053,True,2008.2034.2053,1014.949828,722.162560,580.0,2,20250807,...,84.0,1764.0,29.400000,1.400000,70.0,060-090,060-090,66.266667,67.666667,"(60, 72]"

In [27]:
def getCondition(x):
    if x.Dataset == 20250724:
        if x.Position < 6:
            return "siLUC1"
        else:
            return "siHAUS6"

    elif x.Dataset == 20250807:
        if x.Position < 5:
            return "siLUC1"
        else:
            return "siHAUS6"

df["Condition"] = df.apply(getCondition, axis = 1)

In [28]:
#selected_df = df[["Dataset", "Source_ID", "Position", "Frame", "Frame_onset", "X", "Y"]]

#selected_df.to_csv(outputFolder + "SelectedDataFrame_MitoticStopwatch_Augmin.csv")

In [29]:
df = df.merge(error_df, how = "outer")
#df.head()

In [30]:
df.to_csv(outputFolder + "MainDataFrame_MitoticStopwatch_Augmin.csv")

print("Finished.")

Finished.